export const US_CITIES = [
  { id: "nyc-ny", city: "New York", state: "NY" },
  { id: "la-ca", city: "Los Angeles", state: "CA" },
  { id: "chi-il", city: "Chicago", state: "IL" },
  { id: "hou-tx", city: "Houston", state: "TX" },
  { id: "phx-az", city: "Phoenix", state: "AZ" },
  { id: "phi-pa", city: "Philadelphia", state: "PA" },
  { id: "sa-tx", city: "San Antonio", state: "TX" },
  { id: "sd-ca", city: "San Diego", state: "CA" },
  { id: "dal-tx", city: "Dallas", state: "TX" },
  { id: "sj-ca", city: "San Jose", state: "CA" },
  { id: "aus-tx", city: "Austin", state: "TX" },
  { id: "jax-fl", city: "Jacksonville", state: "FL" },
  { id: "fw-tx", city: "Fort Worth", state: "TX" },
  { id: "col-oh", city: "Columbus", state: "OH" },
  { id: "cha-nc", city: "Charlotte", state: "NC" },
  { id: "sf-ca", city: "San Francisco", state: "CA" },
  { id: "ind-in", city: "Indianapolis", state: "IN" },
  { id: "sea-wa", city: "Seattle", state: "WA" },
  { id: "den-co", city: "Denver", state: "CO" },
  { id: "dc-dc", city: "Washington", state: "DC" },
  { id: "bos-ma", city: "Boston", state: "MA" },
  { id: "ep-tx", city: "El Paso", state: "TX" },
  { id: "nas-tn", city: "Nashville", state: "TN" },
  { id: "det-mi", city: "Detroit", state: "MI" },
  { id: "okc-ok", city: "Oklahoma City", state: "OK" },
  { id: "por-or", city: "Portland", state: "OR" },
  { id: "lv-nv", city: "Las Vegas", state: "NV" },
  { id: "mem-tn", city: "Memphis", state: "TN" },
  { id: "lou-ky", city: "Louisville", state: "KY" },
  { id: "bal-md", city: "Baltimore", state: "MD" },
  { id: "mil-wi", city: "Milwaukee", state: "WI" },
  { id: "abq-nm", city: "Albuquerque", state: "NM" },
  { id: "tuc-az", city: "Tucson", state: "AZ" },
  { id: "fre-ca", city: "Fresno", state: "CA" },
  { id: "sac-ca", city: "Sacramento", state: "CA" },
  { id: "kc-mo", city: "Kansas City", state: "MO" },
  { id: "mesa-az", city: "Mesa", state: "AZ" },
  { id: "atl-ga", city: "Atlanta", state: "GA" },
  { id: "oma-ne", city: "Omaha", state: "NE" },
  { id: "cs-co", city: "Colorado Springs", state: "CO" },
  { id: "ral-nc", city: "Raleigh", state: "NC" },
  { id: "lb-ca", city: "Long Beach", state: "CA" },
  { id: "vb-va", city: "Virginia Beach", state: "VA" },
  { id: "mia-fl", city: "Miami", state: "FL" },
  { id: "oak-ca", city: "Oakland", state: "CA" },
  { id: "min-mn", city: "Minneapolis", state: "MN" },
  { id: "tul-ok", city: "Tulsa", state: "OK" },
  { id: "bak-ca", city: "Bakersfield", state: "CA" },
  { id: "wic-ks", city: "Wichita", state: "KS" },
  { id: "arl-tx", city: "Arlington", state: "TX" },
  { id: "aur-co", city: "Aurora", state: "CO" },
  { id: "tam-fl", city: "Tampa", state: "FL" },
  { id: "no-la", city: "New Orleans", state: "LA" },
  { id: "cle-oh", city: "Cleveland", state: "OH" },
  { id: "hon-hi", city: "Honolulu", state: "HI" },
  { id: "ana-ca", city: "Anaheim", state: "CA" },
  { id: "lex-ky", city: "Lexington", state: "KY" },
  { id: "sto-ca", city: "Stockton", state: "CA" },
  { id: "cc-tx", city: "Corpus Christi", state: "TX" },
  { id: "hen-nv", city: "Henderson", state: "NV" },
  { id: "riv-ca", city: "Riverside", state: "CA" },
  { id: "new-nj", city: "Newark", state: "NJ" },
  { id: "sp-mn", city: "Saint Paul", state: "MN" },
  { id: "sa-ca", city: "Santa Ana", state: "CA" },
  { id: "cin-oh", city: "Cincinnati", state: "OH" },
  { id: "irv-ca", city: "Irvine", state: "CA" },
  { id: "orl-fl", city: "Orlando", state: "FL" },
  { id: "pit-pa", city: "Pittsburgh", state: "PA" },
  { id: "sl-mo", city: "St. Louis", state: "MO" },
  { id: "gre-nc", city: "Greensboro", state: "NC" },
  { id: "jc-nj", city: "Jersey City", state: "NJ" },
  { id: "anc-ak", city: "Anchorage", state: "AK" },
  { id: "lin-ne", city: "Lincoln", state: "NE" },
  { id: "pla-tx", city: "Plano", state: "TX" },
  { id: "dur-nc", city: "Durham", state: "NC" },
  { id: "buf-ny", city: "Buffalo", state: "NY" },
  { id: "cha-az", city: "Chandler", state: "AZ" },
  { id: "cv-ca", city: "Chula Vista", state: "CA" },
  { id: "tol-oh", city: "Toledo", state: "OH" },
  { id: "mad-wi", city: "Madison", state: "WI" },
  { id: "gil-az", city: "Gilbert", state: "AZ" },
  { id: "ren-nv", city: "Reno", state: "NV" },
  { id: "fw-in", city: "Fort Wayne", state: "IN" },
  { id: "nlv-nv", city: "North Las Vegas", state: "NV" },
  { id: "sp-fl", city: "St. Petersburg", state: "FL" },
  { id: "lub-tx", city: "Lubbock", state: "TX" },
  { id: "irv-tx", city: "Irving", state: "TX" },
  { id: "lar-tx", city: "Laredo", state: "TX" },
  { id: "ws-nc", city: "Winston-Salem", state: "NC" },
  { id: "che-va", city: "Chesapeake", state: "VA" },
  { id: "gle-az", city: "Glendale", state: "AZ" },
  { id: "gar-tx", city: "Garland", state: "TX" },
  { id: "sco-az", city: "Scottsdale", state: "AZ" },
  { id: "nor-va", city: "Norfolk", state: "VA" },
  { id: "boi-id", city: "Boise", state: "ID" },
  { id: "fre-ca-97", city: "Fremont", state: "CA" },
  { id: "sc-ca", city: "Santa Clarita", state: "CA" },
  { id: "sb-ca", city: "San Bernardino", state: "CA" },
  { id: "bir-al", city: "Birmingham", state: "AL" },
  { id: "hia-fl", city: "Hialeah", state: "FL" },
  { id: "roc-ny", city: "Rochester", state: "NY" },
  { id: "mod-ca", city: "Modesto", state: "CA" },
  { id: "ric-va", city: "Richmond", state: "VA" },
  { id: "hun-al", city: "Huntsville", state: "AL" },
  { id: "dm-ia", city: "Des Moines", state: "IA" },
  { id: "slc-ut", city: "Salt Lake City", state: "UT" },
  { id: "op-ks", city: "Overland Park", state: "KS" },
  { id: "ama-tx", city: "Amarillo", state: "TX" },
  { id: "aug-ga", city: "Augusta", state: "GA" },
  { id: "gr-mi", city: "Grand Rapids", state: "MI" },
  { id: "yon-ny", city: "Yonkers", state: "NY" },
  { id: "hb-ca", city: "Huntington Beach", state: "CA" },
  { id: "tal-fl", city: "Tallahassee", state: "FL" },
  { id: "col-ga", city: "Columbus", state: "GA" },
  { id: "wor-ma", city: "Worcester", state: "MA" },
  { id: "knox-tn", city: "Knoxville", state: "TN" },
  { id: "psl-fl", city: "Port St. Lucie", state: "FL" },
  { id: "gp-tx", city: "Grand Prairie", state: "TX" },
  { id: "bro-tx", city: "Brownsville", state: "TX" },
  { id: "tem-az", city: "Tempe", state: "AZ" },
  { id: "pro-ri", city: "Providence", state: "RI" },
  { id: "cc-fl", city: "Cape Coral", state: "FL" },
  { id: "cha-tn", city: "Chattanooga", state: "TN" },
  { id: "sr-ca", city: "Santa Rosa", state: "CA" },
  { id: "rc-ca", city: "Rancho Cucamonga", state: "CA" },
  { id: "oce-ca", city: "Oceanside", state: "CA" },
  { id: "sf-sd", city: "Sioux Falls", state: "SD" },
  { id: "gg-ca", city: "Garden Grove", state: "CA" },
  { id: "ont-ca", city: "Ontario", state: "CA" },
  { id: "van-wa", city: "Vancouver", state: "WA" },
  { id: "eg-ca", city: "Elk Grove", state: "CA" },
  { id: "peo-az", city: "Peoria", state: "AZ" },
  { id: "lan-ca", city: "Lancaster", state: "CA" },
  { id: "cor-ca", city: "Corona", state: "CA" },
  { id: "eug-or", city: "Eugene", state: "OR" },
  { id: "sal-or", city: "Salem", state: "OR" },
  { id: "pal-ca", city: "Palmdale", state: "CA" },
  { id: "sal-ca", city: "Salinas", state: "CA" },
  { id: "spr-ma", city: "Springfield", state: "MA" },
  { id: "pas-tx", city: "Pasadena", state: "TX" },
  { id: "roc-il", city: "Rockford", state: "IL" },
  { id: "pom-ca", city: "Pomona", state: "CA" },
  { id: "hay-ca", city: "Hayward", state: "CA" },
  { id: "fc-co", city: "Fort Collins", state: "CO" },
  { id: "jol-il", city: "Joliet", state: "IL" },
  { id: "esc-ca", city: "Escondido", state: "CA" },
  { id: "kc-ks", city: "Kansas City", state: "KS" },
  { id: "tor-ca", city: "Torrance", state: "CA" },
  { id: "bri-ct", city: "Bridgeport", state: "CT" },
  { id: "ale-va", city: "Alexandria", state: "VA" },
  { id: "sun-ca", city: "Sunnyvale", state: "CA" },
  { id: "cary-nc", city: "Cary", state: "NC" },
  { id: "lak-co", city: "Lakewood", state: "CO" },
  { id: "hol-fl", city: "Hollywood", state: "FL" },
  { id: "pat-nj", city: "Paterson", state: "NJ" },
  { id: "nap-il", city: "Naperville", state: "IL" },
  { id: "of-oh", city: "Olmsted Falls", state: "OH" }
];

export const NICHES = [
  { id: "healthcare.dentist", label: "Dentist" },
  { id: "catering.restaurant", label: "Restaurant" },
  { id: "service.financial.lawyer", label: "Lawyer" },
  { id: "healthcare.doctor", label: "Medical Doctor" },
  { id: "service.beauty", label: "Beauty Salon" },
  { id: "service.fitness", label: "Gym / Fitness" },
  { id: "commercial.shopping_mall", label: "Retail / Shop" },
  { id: "service.car_repair", label: "Auto Repair" },
  { id: "education.school", label: "Private School" },
  { id: "accommodation.hotel", label: "Hotel" }
];
